{- HLINT ignore "Use camelCase" -}

-- | lisp-test.hs - test for lisp generated by claude
--
-- Tests parser combinator primitives, S-expression
-- parsing, and Lisp evaluation (arithmetic, comparison, if, car/cdr/cons,
-- define, lambda, recursion, let, begin, hardware FFI).

module Main(main, hs_main) where

import Prelude hiding (putStr, putStrLn, getLine)
import Control.Applicative (many)
import Control.Concurrent.MVar
import qualified UART
import qualified GPIO
import qualified Timer
import Parse
import Lisp

foreign export ccall hs_main :: IO ()

main :: IO ()
main = hs_main

hs_main :: IO ()
hs_main = do
    UART.putStrLn "Lisp Test: Parser Combinators + Lisp Interpreter"
    UART.putStrLn ""

    -- ===== Parser combinator tests =====
    UART.putStrLn "--- Parser Combinator Tests ---"
    p1  <- testP "parse natural 42"    (parse natural "42")    (Just 42)
    p2  <- testP "parse natural 0"     (parse natural "0")     (Just 0)
    p3  <- testP "parse integer -7"    (parse integer "-7")    (Just (-7))
    p4  <- testP "parse integer 123"   (parse integer "123")   (Just 123)
    p5  <- testP "parse char 'a'"      (parse (char 'a') "a")  (Just 'a')
    p6  <- testP "parse char fail"     (parse (char 'a') "b")  (Nothing :: Maybe Char)
    p7  <- testP "parse string"        (parse (string "hello") "hello") (Just "hello")
    p8  <- testP "parse many digits"   (parse (many digit) "123abc") Nothing
    p9  <- testP "parse many digits (runParser)" (fmap fst (runParser (many digit) "123abc")) (Just "123")
    p10 <- testP "parse choice"        (parse (choice [char 'a', char 'b', char 'c']) "b") (Just 'b')
    p11 <- testP "parse sepBy"         (fmap fst (runParser (sepBy natural (char ',')) "1,2,3")) (Just [1,2,3])
    p12 <- testP "parse between"       (parse (between (char '(') (char ')') natural) "(42)") (Just 42)
    UART.putStrLn ""

    let pPass = countTrue [p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12]
    let pTotal = 12

    -- ===== S-expression parser tests =====
    UART.putStrLn "--- S-Expression Parser Tests ---"
    s1  <- testLispParse "atom"           "hello"       "hello"
    s2  <- testLispParse "number"         "42"          "42"
    s3  <- testLispParse "negative"       "-7"          "-7"
    s4  <- testLispParse "bool true"      "#t"          "#t"
    s5  <- testLispParse "bool false"     "#f"          "#f"
    s6  <- testLispParse "string"         "\"hi\""      "\"hi\""
    s7  <- testLispParse "simple list"    "(+ 1 2)"     "(+ 1 2)"
    s8  <- testLispParse "nested list"    "(if (= x 0) 1 (* x 2))" "(if (= x 0) 1 (* x 2))"
    s9  <- testLispParse "quote"          "'foo"        "(quote foo)"
    s10 <- testLispParse "empty list"     "()"          "()"
    UART.putStrLn ""

    let sPass = countTrue [s1,s2,s3,s4,s5,s6,s7,s8,s9,s10]
    let sTotal = 10

    -- ===== Evaluator tests =====
    UART.putStrLn "--- Evaluator Tests ---"
    env <- defaultEnv

    e1  <- testEval env "add"              "(+ 1 2)"           "3"
    e2  <- testEval env "multiply"         "(* 3 4)"           "12"
    e3  <- testEval env "subtract"         "(- 10 3)"          "7"
    e4  <- testEval env "nested arith"     "(+ (* 2 3) (- 10 4))" "12"
    e5  <- testEval env "compare eq"       "(= 5 5)"           "#t"
    e6  <- testEval env "compare lt"       "(< 3 5)"           "#t"
    e7  <- testEval env "compare gt"       "(> 3 5)"           "#f"
    e8  <- testEval env "if true"          "(if #t 1 2)"       "1"
    e9  <- testEval env "if false"         "(if #f 1 2)"       "2"
    e10 <- testEval env "car"              "(car (list 1 2 3))" "1"
    e11 <- testEval env "cdr"              "(cdr (list 1 2 3))" "(2 3)"
    e12 <- testEval env "cons"             "(cons 0 (list 1 2))" "(0 1 2)"
    e13 <- testEval env "null? empty"      "(null? (list))"    "#t"
    e14 <- testEval env "null? non-empty"  "(null? (list 1))"  "#f"
    e15 <- testEval env "length"           "(length (list 1 2 3))" "3"
    e16 <- testEval env "string-append"    "(string-append \"hello\" \" \" \"world\")" "\"hello world\""
    e17 <- testEval env "number->string"   "(number->string 42)" "\"42\""
    e18 <- testEval env "not true"         "(not #t)"          "#f"
    e19 <- testEval env "not false"        "(not #f)"          "#t"
    e20 <- testEval env "boolean?"         "(boolean? #t)"     "#t"
    UART.putStrLn ""

    let ePass = countTrue [e1,e2,e3,e4,e5,e6,e7,e8,e9,e10,e11,e12,e13,e14,e15,e16,e17,e18,e19,e20]
    let eTotal = 20

    -- ===== Define and lambda tests =====
    UART.putStrLn "--- Define & Lambda Tests ---"

    -- Define a variable
    d1 <- testEvalOk env "define x" "(define x 42)"
    d2 <- testEval env "use x" "x" "42"

    -- Define a function
    d3 <- testEvalOk env "define double" "(define (double n) (* n 2))"
    d4 <- testEval env "call double" "(double 21)" "42"

    -- Lambda
    d5 <- testEval env "lambda call" "((lambda (x y) (+ x y)) 3 4)" "7"

    -- Let
    d6 <- testEval env "let" "(let ((a 10) (b 20)) (+ a b))" "30"

    -- Begin
    d7 <- testEval env "begin" "(begin 1 2 3)" "3"

    -- Recursive factorial
    d8 <- testEvalOk env "define fact" "(define (fact n) (if (= n 0) 1 (* n (fact (- n 1)))))"
    d9 <- testEval env "fact 5" "(fact 5)" "120"
    d10 <- testEval env "fact 10" "(fact 10)" "3628800"

    -- Cond
    d11 <- testEval env "cond" "(cond ((= 1 2) 10) ((= 1 1) 20) (else 30))" "20"
    UART.putStrLn ""

    let dPass = countTrue [d1,d2,d3,d4,d5,d6,d7,d8,d9,d10,d11]
    let dTotal = 11

    -- ===== Hardware FFI tests =====
    UART.putStrLn "--- Hardware FFI Tests ---"
    h1 <- testEvalOk env "gpio-write" "(gpio-write 27 1)"
    Timer.delayMs 100
    h2 <- testEvalOk env "gpio-write off" "(gpio-write 27 0)"
    h3 <- testEvalOk env "delay" "(delay 50)"
    UART.putStrLn ""

    let hPass = countTrue [h1,h2,h3]
    let hTotal = 3

    -- ===== Summary =====
    let totalPass = pPass + sPass + ePass + dPass + hPass
    let totalTests = pTotal + sTotal + eTotal + dTotal + hTotal

    UART.putStrLn "==========================="
    UART.putStr "Parser combinators: "
    printScore pPass pTotal
    UART.putStr "S-expression parser: "
    printScore sPass sTotal
    UART.putStr "Evaluator:          "
    printScore ePass eTotal
    UART.putStr "Define/Lambda:      "
    printScore dPass dTotal
    UART.putStr "Hardware FFI:       "
    printScore hPass hTotal
    UART.putStrLn "==========================="
    UART.putStr "Total: "
    printScore totalPass totalTests

    UART.putStrLn ""
    if totalPass == totalTests
      then UART.putStrLn "ALL TESTS PASSED"
      else UART.putStrLn "SOME TESTS FAILED"

-- ================================================================
-- Test helpers
-- ================================================================

testP :: (Eq a, Show a) => String -> Maybe a -> Maybe a -> IO Bool
testP name got expected = do
    let ok = got == expected
    UART.putStr "  "
    UART.putStr name
    UART.putStr ": "
    if ok
      then UART.putStrLn "ok"
      else do
        UART.putStr "FAIL (got "
        UART.putStr (showMaybe got)
        UART.putStr ", expected "
        UART.putStr (showMaybe expected)
        UART.putStrLn ")"
    return ok

showMaybe :: Show a => Maybe a -> String
showMaybe Nothing  = "Nothing"
showMaybe (Just x) = show x

testLispParse :: String -> String -> String -> IO Bool
testLispParse name input expected = do
    let result = lispParse input
    let ok = case result of
               Right val -> showVal val == expected
               Left _    -> False
    UART.putStr "  "
    UART.putStr name
    UART.putStr ": "
    if ok
      then UART.putStrLn "ok"
      else do
        UART.putStr "FAIL (got "
        case result of
          Right val -> UART.putStr (showVal val)
          Left err  -> do UART.putStr "Error: "; UART.putStr err
        UART.putStr ", expected "
        UART.putStr expected
        UART.putStrLn ")"
    return ok

testEval :: Env -> String -> String -> String -> IO Bool
testEval env name input expected = do
    case lispParse input of
      Left err -> do
        UART.putStr "  "
        UART.putStr name
        UART.putStr ": FAIL (parse error: "
        UART.putStr err
        UART.putStrLn ")"
        return False
      Right expr -> do
        result <- eval env expr
        let ok = case result of
                   Right val -> showVal val == expected
                   Left _    -> False
        UART.putStr "  "
        UART.putStr name
        UART.putStr ": "
        if ok
          then UART.putStrLn "ok"
          else do
            UART.putStr "FAIL (got "
            case result of
              Right val -> UART.putStr (showVal val)
              Left err  -> do UART.putStr "Error: "; UART.putStr err
            UART.putStr ", expected "
            UART.putStr expected
            UART.putStrLn ")"
        return ok

testEvalOk :: Env -> String -> String -> IO Bool
testEvalOk env name input = do
    case lispParse input of
      Left err -> do
        UART.putStr "  "
        UART.putStr name
        UART.putStr ": FAIL (parse error: "
        UART.putStr err
        UART.putStrLn ")"
        return False
      Right expr -> do
        result <- eval env expr
        let ok = case result of
                   Right _ -> True
                   Left _  -> False
        UART.putStr "  "
        UART.putStr name
        UART.putStr ": "
        if ok
          then UART.putStrLn "ok"
          else do
            case result of
              Left err -> do UART.putStr "FAIL ("; UART.putStr err; UART.putStrLn ")"
              _        -> UART.putStrLn "FAIL"
        return ok

countTrue :: [Bool] -> Int
countTrue = length . filter id

printScore :: Int -> Int -> IO ()
printScore pass total = do
    UART.putUint (fromIntegral pass)
    UART.putStr "/"
    UART.putUint (fromIntegral total)
    UART.putStrLn ""
