{- HLINT ignore "Use camelCase" -}
-- | nrf-test.hs - two nrf loopback test generated by claude
--                 based on nrf lab tests
--
-- Mirrors cs140e NRF lab tests:
--   - 0-ack-check.c: init both NRFs, verify STATUS/RF_CH registers
--   - 1-one-way-no-ack-4bytes.c: server sends packets, client receives (no ACK)
--   - 2-one-way-ack-4bytes.c: server sends packets, client receives (with ACK)
--
-- Hardware setup: two NRF24L01+ modules on the same SPI0 bus:
--   Left  (server): CE=6, SPI chip=0, rxaddr=0xd5d5d5
--   Right (client): CE=5, SPI chip=1, rxaddr=0xe5e5e5

module Main(main, hs_main) where

import Prelude hiding (putStr, putStrLn)
import Data.Word
import Data.Bits ((.&.), (.|.), shiftL, shiftR)
import Data.Char (chr, ord)
import qualified UART
import qualified NRF
import qualified Timer
import qualified NetChan (Msg(..), encode, decode)
import GHC.IO.Device (IODevice(close))

foreign export ccall hs_main :: IO ()

main :: IO ()
main = hs_main

-- ================================================================
-- NRF register addresses (not exported from NRF module)
-- ================================================================

regSTATUS :: Word8
regSTATUS = 0x07

regRF_CH :: Word8
regRF_CH = 0x05

-- ================================================================
-- Hex byte printing (UART.putHex prints full 32-bit)
-- ================================================================

putHexByte :: Word8 -> IO ()
putHexByte b = do
    UART.putStr "0x"
    let hi = b `shiftR` 4
    let lo = b .&. 0x0F
    UART.putByte (fromIntegral (hexDigit hi))
    UART.putByte (fromIntegral (hexDigit lo))
  where
    hexDigit :: Word8 -> Word8
    hexDigit n
      | n < 10    = n + fromIntegral (ord '0')
      | otherwise = n - 10 + fromIntegral (ord 'a')

putHexBytes :: [Word8] -> IO ()
putHexBytes [] = return ()
putHexBytes [x] = putHexByte x
putHexBytes (x:xs) = do
    putHexByte x
    UART.putStr ", "
    putHexBytes xs

-- ================================================================
-- Receive with timeout
-- ================================================================

recvWithTimeout :: NRF.NrfHandle -> Word32 -> IO (Maybe [Word8])
recvWithTimeout nh timeoutUs = do
    start <- Timer.getTimeUs
    go start
  where
    go start = do
        mpkt <- NRF.nrfRecv nh
        case mpkt of
            Just pkt -> return (Just pkt)
            Nothing -> do
                now <- Timer.getTimeUs
                if now - start > timeoutUs
                    then return Nothing
                    else do
                        Timer.delayMs 1
                        go start

-- ================================================================
-- Counter encoding (first 4 bytes of payload, little-endian)
-- ================================================================

encodeCounter :: Word32 -> [Word8]
encodeCounter w =
    [ fromIntegral (w .&. 0xFF)
    , fromIntegral ((w `shiftR` 8) .&. 0xFF)
    , fromIntegral ((w `shiftR` 16) .&. 0xFF)
    , fromIntegral ((w `shiftR` 24) .&. 0xFF)
    ]

decodeCounter :: [Word8] -> Word32
decodeCounter (a:b:c:d:_) =
    fromIntegral a
    .|. (fromIntegral b `shiftL` 8)
    .|. (fromIntegral c `shiftL` 16)
    .|. (fromIntegral d `shiftL` 24)
decodeCounter _ = 0xFFFFFFFF

-- ================================================================
-- Send test: server sends N packets, client receives and verifies
-- ================================================================

sendTestNoAck :: NRF.NrfHandle -> NRF.NrfHandle -> Int -> IO Bool
sendTestNoAck server client n = go 1 True
  where
    go i allOk
      | i > n = return allOk
      | otherwise = do
          let payload = encodeCounter (fromIntegral i)
          _ <- NRF.nrfSendNoAck server payload
          Timer.delayMs 5
          mpkt <- recvWithTimeout client 100000
          case mpkt of
            Just pkt -> do
              let val = decodeCounter pkt
              let match = val == fromIntegral i
              UART.putStr "  Sent "
              UART.putUint (fromIntegral i)
              UART.putStr "/"
              UART.putUint (fromIntegral n)
              if match
                then UART.putStrLn "... received ok"
                else do
                  UART.putStr "... MISMATCH (got "
                  UART.putUint val
                  UART.putStrLn ")"
              go (i + 1) (allOk && match)
            Nothing -> do
              UART.putStr "  Sent "
              UART.putUint (fromIntegral i)
              UART.putStr "/"
              UART.putUint (fromIntegral n)
              UART.putStrLn "... TIMEOUT"
              go (i + 1) False

sendTestAck :: NRF.NrfHandle -> NRF.NrfHandle -> Int -> IO Bool
sendTestAck server client n = go 1 True
  where
    go i allOk
      | i > n = return allOk
      | otherwise = do
          let payload = encodeCounter (fromIntegral i)
          ok <- NRF.nrfSend server payload
          Timer.delayMs 5
          mpkt <- recvWithTimeout client 100000
          case mpkt of
            Just pkt -> do
              let val = decodeCounter pkt
              let match = val == fromIntegral i && ok
              UART.putStr "  Sent "
              UART.putUint (fromIntegral i)
              UART.putStr "/"
              UART.putUint (fromIntegral n)
              if match
                then UART.putStrLn "... received ok (ACK)"
                else do
                  UART.putStr "... FAIL (got "
                  UART.putUint val
                  UART.putStr ", ack="
                  UART.putStr (if ok then "yes" else "no")
                  UART.putStrLn ")"
              go (i + 1) (allOk && match)
            Nothing -> do
              UART.putStr "  Sent "
              UART.putUint (fromIntegral i)
              UART.putStr "/"
              UART.putUint (fromIntegral n)
              UART.putStrLn "... TIMEOUT"
              go (i + 1) False

-- ================================================================
-- NetChan encode/decode test (through the radio)
-- ================================================================

netChanTest :: NRF.NrfHandle -> NRF.NrfHandle -> IO Bool
netChanTest server client = do
    let msg = NetChan.MsgStr "hello"
    let encoded = NetChan.encode msg
    UART.putStr "  Encoded MsgStr \"hello\" -> ["
    putHexBytes encoded
    UART.putStrLn "]"

    -- Send encoded bytes through radio
    ok <- NRF.nrfSend server encoded
    if not ok
      then do
        UART.putStrLn "  Send failed!"
        return False
      else do
        Timer.delayMs 5
        mpkt <- recvWithTimeout client 100000
        case mpkt of
          Just pkt -> do
            let decoded = NetChan.decode pkt
            case decoded of
              Just (NetChan.MsgStr s) -> do
                UART.putStr "  Decoded: MsgStr \""
                UART.putStr s
                UART.putStr "\""
                if s == "hello"
                  then do UART.putStrLn " ok"; return True
                  else do UART.putStrLn " FAIL (wrong string)"; return False
              Just _ -> do
                UART.putStrLn "  FAIL (decoded wrong message type)"
                return False
              Nothing -> do
                UART.putStrLn "  FAIL (decode returned Nothing)"
                return False
          Nothing -> do
            UART.putStrLn "  FAIL (recv timeout)"
            return False

-- ================================================================
-- Stats printing
-- ================================================================

printStats :: String -> NRF.NrfHandle -> IO ()
printStats name nh = do
    stats <- NRF.nrfStats nh
    UART.putStr "  "
    UART.putStr name
    UART.putStr ": sent="
    UART.putUint (NRF.statsSent stats)
    UART.putStr ", recv="
    UART.putUint (NRF.statsRecv stats)
    UART.putStr ", retrans="
    UART.putUint (NRF.statsRetrans stats)
    UART.putStr ", lost="
    UART.putUint (NRF.statsLost stats)
    UART.putStrLn ""

-- ================================================================
-- Main test
-- ================================================================

hs_main :: IO ()
hs_main = do
    UART.putStrLn "NRF Test: Two-NRF loopback on single Pi"
    UART.putStrLn ""

    -- ===== Phase 1: Init no-ack mode + SPI verification =====
    UART.putStrLn "Initializing server NRF (left, CE=6, SPI=0)..."
    let noAckServerCfg = NRF.serverConfig { NRF.nrfPayloadSize = 32, NRF.nrfAcked = False }
    server <- NRF.nrfInit noAckServerCfg

    UART.putStrLn "Initializing client NRF (right, CE=5, SPI=1)..."
    let noAckClientCfg = NRF.clientConfig { NRF.nrfPayloadSize = 32, NRF.nrfAcked = False }
    client <- NRF.nrfInit noAckClientCfg

    -- STATUS register check (expect 0x0E: RX_P_NO=111, no interrupts)
    srvStatus <- NRF.nrfGet8 server regSTATUS
    UART.putStr "Server STATUS: "
    putHexByte srvStatus
    if srvStatus == 0x0E
      then UART.putStrLn "  ok"
      else do UART.putStr "  FAIL (expected "; putHexByte 0x0E; UART.putStrLn ")"

    cliStatus <- NRF.nrfGet8 client regSTATUS
    UART.putStr "Client STATUS: "
    putHexByte cliStatus
    if cliStatus == 0x0E
      then UART.putStrLn "  ok"
      else do UART.putStr "  FAIL (expected "; putHexByte 0x0E; UART.putStrLn ")"

    -- RF_CH register check (expect 113)
    srvCh <- NRF.nrfGet8 server regRF_CH
    UART.putStr "Server RF_CH: "
    UART.putUint (fromIntegral srvCh)
    if srvCh == 113
      then UART.putStrLn "  ok"
      else UART.putStrLn "  FAIL (expected 113)"

    cliCh <- NRF.nrfGet8 client regRF_CH
    UART.putStr "Client RF_CH: "
    UART.putUint (fromIntegral cliCh)
    if cliCh == 113
      then UART.putStrLn "  ok"
      else UART.putStrLn "  FAIL (expected 113)"

    let spiOk = srvStatus == 0x0E && cliStatus == 0x0E
                && srvCh == 113 && cliCh == 113

    UART.putStrLn ""

    -- ===== Phase 2: One-way no-ack test (10 packets) =====
    UART.putStrLn "--- One-way no-ack test (10 packets) ---"
    noAckOk <- sendTestNoAck server client 10
    UART.putStrLn ""

    -- Print no-ack stats
    UART.putStrLn "--- No-ack stats ---"
    printStats "Server" server
    printStats "Client" client
    UART.putStrLn ""

    -- ===== Phase 3: Re-init with ACK for ack + NetChan tests =====
    UART.putStrLn "Reinitializing NRFs (ack mode)..."
    let ackServerCfg = NRF.serverConfig { NRF.nrfPayloadSize = 32 }
    server2 <- NRF.nrfInit ackServerCfg

    let ackClientCfg = NRF.clientConfig { NRF.nrfPayloadSize = 32 }
    client2 <- NRF.nrfInit ackClientCfg
    UART.putStrLn ""

    -- ===== Phase 4: One-way ack test (10 packets) =====
    UART.putStrLn "--- One-way ack test (10 packets) ---"
    ackOk <- sendTestAck server2 client2 10
    UART.putStrLn ""

    -- ===== Phase 5: NetChan encode/decode test =====
    UART.putStrLn "--- NetChan encode/decode test ---"
    netChanOk <- netChanTest server2 client2
    UART.putStrLn ""

    -- ===== Phase 6: Final stats =====
    UART.putStrLn "--- Stats ---"
    printStats "Server" server2
    printStats "Client" client2
    UART.putStrLn ""
  
    -- ===== Verdict =====
    if spiOk && noAckOk && ackOk && netChanOk
      then UART.putStrLn "ALL TESTS PASSED"
      else UART.putStrLn "SOME TESTS FAILED"
